version: '3'
services:
  app:
    build: .
    ports:
     - "3000:3000"
    depends_on:
     - "redis"
     - "postgres"
    entrypoint: ./docker-entrypoint.sh
    working_dir: /myapp
    environment:
     ## Infra Env
     - POSTGRES_USER=bowo
     - POSTGRES_PASSWORD=password
     - POSTGRES_HOST=postgres
     - REDIS_URL=redis://redis:6379/15
    volumes:
      - .:/myapp
  redis:
    image: "redis:3.2.11-alpine"
  postgres:
    build: ./db
    environment:
     - POSTGRES_USER=bowo
     - POSTGRES_PASSWORD=password
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: